-- Country table for shipping
-- Add this to the database

CREATE TABLE `country` (
  `Code` varchar(2) NOT NULL,
  `Name` varchar(100) NOT NULL,
  PRIMARY KEY (`Code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert country data
INSERT INTO `country` (`Code`, `Name`) VALUES
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AR', 'Argentina'),
('AU', 'Australia'),
('AT', 'Austria'),
('BD', 'Bangladesh'),
('BE', 'Belgium'),
('BR', 'Brazil'),
('BG', 'Bulgaria'),
('CA', 'Canada'),
('CL', 'Chile'),
('CN', 'China'),
('CO', 'Colombia'),
('CR', 'Costa Rica'),
('HR', 'Croatia'),
('CZ', 'Czech Republic'),
('DK', 'Denmark'),
('EG', 'Egypt'),
('EE', 'Estonia'),
('FI', 'Finland'),
('FR', 'France'),
('DE', 'Germany'),
('GR', 'Greece'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IL', 'Israel'),
('IT', 'Italy'),
('JP', 'Japan'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KR', 'South Korea'),
('KW', 'Kuwait'),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LT', 'Lithuania'),
('MY', 'Malaysia'),
('MX', 'Mexico'),
('MA', 'Morocco'),
('NL', 'Netherlands'),
('NZ', 'New Zealand'),
('NG', 'Nigeria'),
('NO', 'Norway'),
('PK', 'Pakistan'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PL', 'Poland'),
('PT', 'Portugal'),
('QA', 'Qatar'),
('RO', 'Romania'),
('RU', 'Russia'),
('SA', 'Saudi Arabia'),
('RS', 'Serbia'),
('SG', 'Singapore'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('ZA', 'South Africa'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('TW', 'Taiwan'),
('TH', 'Thailand'),
('TR', 'Turkey'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates'),
('GB', 'United Kingdom'),
('US', 'United States'),
('VE', 'Venezuela'),
('VN', 'Vietnam');
